export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

export const MODIFICAR_THEME = 'MODIFICAR_THEME';